branches:
  only:
    - master
env:
  global:
    - secure: "tqMICNzlFxX9rVnEeFITTjw8Dy+PTnQFNV7c1/LjLjlLKGVr6okRs/BQTpLBPogHadKazLdNcX40ClAMA1Tfnqk3qZ0u1lfqEDGT6cj85vHmiAEMnyS1p5iKQjC3xt/+CurpaBj35Um72I2rzG3uIcpDK0YubWHI3uzVu30v0+ex0iOELMi9pCozntLjnRxPruzL+5UTEce7s+zWM3TiZUz5Ivt+Tn3jZZlq3yHFL3uNNnNj166R4LL0qesfMB9uFmuXrM3b24qaZeFNG9/kowERx42bXeI4A4y6rhOZnjN4Gs3bVnxbGVK3QbYy4wSpJIrdZ/zhfQg5jlnCeu9TsKGT6HjEXZjvqMABiO1oBrneRRsqzGHI3rvYnPVp6wEyYzRCCI0joNyHi0KBvuzKTzOAuOhYcn1+y+MDBpRfbQtjpMsG25UmLG+sxJ9Hlhq9PLp4+UnRQvgPxJTcATNKCTepV2RTGEb4xixYYE92kPZfP3imE9WNDA5larKBFXFg05E50miLbAL/lmcbcG5B+q+YMY0X2lE1BkYrdFoTsfVBSIC7IsMAqWsBJEbFjGjsOsw4vpLkBA+TN1hPOcrBoVQjMwids2+8flg3iw7HkaSsDzdpq/x2hk7X9AsQZE/crVCjBDUWMdKg9Vhtd1oL7TOKlsN3RCCfDIZHTwLDgiI="
    - secure: "m0mV1wXo0WpD42hXzOS5jYcWwNzbXuhESHp6f9kQxruHWED7+Fhdj9VQNq8aAMcilDeAD+jnMZ/jSaHyakWO/FXNSprUiA8aP9C8pKmAhdFetOc9rsTu43rKB5OIMAr6EET+Q5r6usJyn0Pic1oqg0gKhD5AhKsJ+4vkQOV6OM0BriUfYbMgqGz5j5/z3EUIo+XeXSguh4bI9bC+rwz39IMwVZ4eB34CYGFINDUk8b72zDCM2BsQD+WffotbkjxqzR4zWzJIDMERDnDcqE22Yu+h5mFYjE7FM0chT7mz+DlVwnuV/rYD/+O3L45jzsrjpeSEosO4AhsnfAwdVgmPE8XQYD6KD4GUWwIPra4+GChfLkucfi8YlbxC91R0yZyFGmeqEjyPQ3m3UbDi1fVOFmxsVDlBb1XvyMUh1xYfV0pO/HTtHQ2YnHyEYfIAFzNuBnSYr8HEB6eXPGDcZqtp3cInuJv7R9uML5OAw2cpQXCbx/5Rs03l3fOLtoF7jzLk5pmyKoXPr5k0VNL1nsvct4C4+YGM4pVdxE2QJKe1R8EozXm1njrL+vQQtwhVqP+MT5w/uvfDfSrd7ath7cMUnSQefmMRoPxuuGQ9K4ud1NVbBB04wSwxTMNbxmzaVfKSpB9mKrQeXfGuuANn6TscSYIJraSx77IrolpAiltRpnI="
    - secure: "TzRigew/vWzLuyD3S/BeIyl3CIqRqPXVy9HbvLDpW1sOgUK99EJlPwK+uBJsA2ywLoJdaw85/unhsoWxM16WdSoC4BjVi99yenYA725Wrw9A3DA+u2nlWByYQT0bTlSHEdgoU54dnsgo5lqcSzXGEwwuZku8eHRY526wgnLVQxoixowl3fBuf0luC453tGZI5cFoLg0IJsaqoID3gGSe4tHJyFTD46Gf3EIiLeVAK13hcuemGqL5DDpQFVtSHdevFb2WV8yXOvDjXAPopw8JRfSUmrYAvzxt7PzjQ+cJwSbru6oQnVUpafUEcOZSQLBHjvnXJtwz6/UykOIHVgse4LGcx187Ecu1G+UmZm1Y9nGYUEPadzlfnPI3PP+KodppcizSRyl7tBy50G/Z5elKAbcnQnw+ZOssgaYsxwNfM8II7Vj6QB5ClDuSiodT9l+BiZn/+6w2zuqurTokXm8DxhRTZyBnmyeE+HIMByQA6osQuUaAa/vHzuvhtxO8MmuSUXgKOX7v8qgBnc/sWIeqmrcm+mZ8TDMOrEAZU0qSftPcTx/mRuuIco5qbgjyRBxKSPnrd7GMIaZUwcyMmpTsc5377ZRVXgVTaGqjZszmlvK0uvTHRgc2S9imvLN5BLYo4pWWHIZl3MzWktFn7jROkDCKfZegJGuC98z/Q1SLubc="
language: scala
scala:
  - 2.10.4
  - 2.11.7
jdk:
  - oraclejdk7
sudo: required
dist: trusty
cache:
  directories:
    - ~/.ivy2
    - ~/travis-deps
  apt: true
before_install:
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/zookeeper | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/kafka | /bin/sh
  - curl https://raw.githubusercontent.com/PagerDuty/pd-travis-deps/master/cassandra | /bin/sh
  - cd $TRAVIS_BUILD_DIR
  - mkdir ~/.sbt
  - cp .travisci/credentials.sbt ~/.sbt
  - sed -i "s|%{password}|$ARTIFACTORY_PASS|" ~/.sbt/credentials.sbt
before_script:
  - ~/travis-deps/start-zookeeper.sh && sleep 3
  - ~/travis-deps/start-kafka.sh && sleep 3
  - (JVM_OPTS="" ~/travis-deps/start-cassandra.sh && sleep 6)
  - ~/travis-deps/kafka_2.11-0.9.0.1/bin/kafka-topics.sh --create --zookeeper localhost:2181 --replication-factor 1 --partitions 16 --topic scheduler-integration-test-queue

script:
  - sbt -Dsbt.log.noformat=true -sbt-dir ~/.sbt ++$TRAVIS_SCALA_VERSION test
after_success:
- sh "$TRAVIS_BUILD_DIR/.travis.release.sh"
